services:
  postgres:
    image: 'postgres'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - ./env/db.env
  queue:
    image: 'rabbitmq:management'
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - queue_data:/var/lib/rabbitmq
      - ./conf/queue/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./conf/queue/definitions.json:/etc/rabbitmq/definitions.json
  client:
    build: ./client
    ports: 
      - '8080:8080'
    depends_on:
      postgres:
        condition: service_healthy
      queue:
        condition: service_healthy

volumes:
  data:
  queue_data:
