spring:
  application:
    name: client
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: queue
    port: 5672
    username: guest
    password: guest